### ISSUE TITLE
What is the due date of HW1

### ISSUE THREAD

**Issue by simnalamburt** [snu-sf-class/pp202002#2]
What is the due date of HW1?

**Comment by MerHS** [comment]
10/9 23:59입니다.

제출 기한은 숙제 배포와 동시에 공지사항에 같이 공지하고 있습니다.

**Comment by simnalamburt** [comment]
미래의 과제에서 듀를 안 놓치기 위해 추가적으로 여쭙습니다. 혹시 듀가 명시되어있다는 공지사항이 이 공지사항을 말씀하시는게 맞나요? 아래의 글에는 듀가 보이지 않습니다.

![9B5C8092-F96D-4EBD-843E-A6B2B9D7C94F](https://user-images.githubusercontent.com/4435445/94464030-d3b05d00-01f8-11eb-9ac0-47d91bf002a2.jpeg)

**Comment by MerHS** [comment]
여기서 공지는 이 깃헙 레포의 메인페이지인 [README.md](https://github.com/snu-sf-class/pp202002)를 의미합니다. 

etl은 수강생 알림을 위해 사용하였으며 과제나 시험 일정 등의 상세한 공지사항은 깃헙을 확인해주시기 바랍니다.
