### ISSUE TITLE
숙제 2 due date 오타

### ISSUE THREAD

**Issue by simnalamburt** [snu-sf-class/pp202002#20]
Due date가 잘못된거같은데 확인 부탁드립니다

**Comment by MerHS** [comment]
수정하였습니다

**Comment by d5br5** [comment]
> 수정하였습니다

아직 11/20(목) 으로 되어 있습니다.
11/19(목) 까지인가요, 11/20(금) 까지인가요?

**Comment by MerHS** [comment]
금요일이 맞습니다

**Comment by simnalamburt** [comment]
Closed by https://github.com/snu-sf-class/pp202002/commit/2b9a601c3110f11900aa290da2e486c15f960945
