### ISSUE TITLE
[Exercise 2: Regular Expressions] Can an empty string be a part of input since `EEpsilon` is also `Exp`?

### ISSUE THREAD

**Issue by lucetre** [snu-sf-class/pp202002#26]
```(*) Syntax of Exp (see Data.scala)
    E -> a      (single alphanumeric character)
       | (EE)   (concatenation)
       | (E|E)  (or)
       | (E)*   (repetition / kleene star)
```
### Question 1
Data.scala의 `Exp` 안에 빈 문자열을 나타내는 `EEpsilon`이 존재하여 
Exercise 2-1의 입력 문자열로 `(x)`도 가능한지 묻고 싶습니다.
된다면 `(x)`는 `EConcat(EChar('x'), EEpsilon)` 와 `EConcat(EEpsilon, EChar('x'))` 중 무엇인가요?

### Question 2
Exercise 2-2의 Regex Input으로 `converter`를 쓰지 않은 형태인 `EConcat(EEpsilon, EChar('x'))` 도 가능한지 묻고 싶습니다.
(`(EE) | (E|E) | (E)*` 각각의 경우에 대해 `E`가 `EEpsilon`인 경우)

**Comment by MerHS** [comment]
1. 문제에서 인식해야 하는 값은 저 위의 문법으로 정의할 수 있는 값만으로 한정됩니다. 
즉, `(x)`와 같은 입력은 `EError`가 되어야 합니다.
`EEpsilon`이 되어야 하는 값은 빈문자열만으로 한정됩니다.

2. 가능은 하겠으나 입력값의 `EEpsilon`의 존재 유무가 문제 풀이에 영향을 미치진 않을 것입니다.
일단은 converter로 변환되어 들어온 input으로 한정해도 무방합니다.
