### ISSUE TITLE
HW2: Can we use `Option` or `Either`?

### ISSUE THREAD

**Issue by simnalamburt** [snu-sf-class/pp202002#39]
`Option`이나 `Either` 타입도 사용이 가능한가요? 만드는게 어려운것도 아니고 과제 취지상 가능해보이기는 하지만 두 타입이 `scala.collections.*`가 아니라 `scala.*` 위치에 있어서 혹시 몰라 여쭤봅니다.

**Comment by MerHS** [comment]
그 두개는 사용 가능하다고 하겠습니다.

이 이외에 scala.*의 자료구조를 사용하시면 안됩니다.

**Comment by simnalamburt** [comment]
감사합니다
