### ISSUE TITLE
What is definition of `n` in Exercise 3 (HW1)

### ISSUE THREAD

**Issue by tyg03485** [snu-sf-class/pp202002#4]
```
   Exercise 3: Ping-pong Ackermann function

   Given a function p and positive integer a and b, implement this function `ppa`: (0 <= n <= 10^6)
   ppa(p, a, b) = p(a, b)               (if a <= 0 or b <= 0)
   ppa(p, a, b) = p(a, ppa(p, a-1, b))  (if p(a, b) is even and a, b > 0)
   ppa(p, a, b) = p(ppa(p, a, b-1), b)  (if p(a, b) is odd and a, b > 0)

```
n 의 정의가 따로 기술되어 있지 않은 것 같아 이슈 올립니다.
0 <= a, b <= 10^6 으로 이해하면 될까요? 아니면 0 <= a+b <= 10^6 으로 이해하면 될까요?

**Comment by MerHS** [comment]
n이 아니라 a, b가 맞습니다.

해당 주석 수정해서 다시 올리겠습니다.

**Comment by koyrkr** [comment]
Hint 1: If n > 0, wrap remained calculations, make it as an anonymous function and pass it to the parameter recursively.
           That anonymous function is called 'Continuation'. You'd better search 'Continuation Passing Style'.

여기서의 n도 a, b라고 이해해도 괜찮을까요?

**Comment by MerHS** [comment]
그렇습니다. 그 부분도 수정하겠습니다.
