### ISSUE TITLE
SYSTEM ERROR에 대한 질문

### ISSUE THREAD

**Issue by sndjg** [snu-sf-class/pp202002#55]
src 폴더 안에 scala 파일을 모두 포함한 뒤 압축하여 제출하였는데 SYSTEM ERROR로 채점이 되지 않았습니다.
SYSTEM ERROR가 뜨는 것은 어떤 경우인가요?
이미 기한이 지나서 이번 과제는 어쩔 수 없더라도 다음 제출을 위해 이유를 알아두어야 할 것 같아서 질문합니다.

**Comment by simnalamburt** [comment]
빌드 결과물까지 다 압축해서 제출하신 것 같습니다. 아마 채점서버 버그로 추정되는데, zip 에 특이한 이름의 파일이 들어있으면 채점에
실패하는 문제가 생기는 것 같습니다.

2020년 12월 5일 (토) 00:09, sndjg <notifications@github.com>님이 작성:

**Comment by sndjg** [comment]
이후에 또 system error가 발생하면 그런 경우도 체크해봐야겠네요. 그렇지만
src.zip
   src
      Data.scala
      Caesar.scala
      Enigma.scala
      Test.scala
위와 같은 구조라면 구성으로 인한 문제는 생길 이유가 없지 않나요?

**Comment by simnalamburt** [comment]
그런경우면 문제가 생기지 않아야하는데 이상하네요.

혹시 macOS에서 기본 압축 유틸리티를 써서 압축하셨나요? 그런 경우라면 `.DS_Store`, `__MACOSX` 같은 특수한 파일들도 함께 압축되는데 이게 문제를 일으켰을수도 있을 것 같습니다.

**Comment by sndjg** [comment]
windows에서 7zip 이용해서 압축했습니다.

**Comment by MerHS** [comment]
학번 또는 이름 알려주시면 확인해보겠습니다

**Comment by sndjg** [comment]
2017-18731입니다

**Comment by MerHS** [comment]
```
object Enigma extends CipherGen[EnigmaSettings] {
  def buildEncryptor(initSetting: EnigmaSettings): Enigma = ???

  def buildDecryptor(initSetting: EnigmaSettings): Enigma = ???
}

class Enigma(/* WRITE YOUR CODE */) extends Encryptor with Decryptor {
  def encrypt(c: Char): (Char, Enigma) = ???

  // Decryption of Enigma machine is same to the Encryption
  def decrypt(c: Char): (Char, Enigma) = encrypt(c)
}
```

Enigma.scala의 구현해야 하는 부분이 `???`로 남아있어 컴파일이 안 되는 문제로 확인되었습니다.

채점을 어떻게 할지는 월요일 이후 교수님과 상의하여 결정하겠습니다.

**Comment by sndjg** [comment]
네 감사합니다.

**Comment by MerHS** [comment]
SYSTEM ERROR로 잘못 나온 문제가 있기 때문에 Enigma만 제외하고 채점 진행하였습니다.

추후 점수 시트에서 점수 확인해주시기 바랍니다.
