### ISSUE TITLE
정수 관련 언어 동작

### ISSUE THREAD

**Issue by simnalamburt** [snu-sf-class/pp202002#77]
programming language E에서의 음수 모듈러 연산이라던가, 인티저 오버플로우시의 동작이라던가, 등등 명시되지 않은 부분들이 여럿 있는데 모두 스칼라 `Int`형의 동작을 그대로 따라한다고 가정해도 될까요?

상식적으로 그럴 것 같지만 과제에 언급이 없어서 확인차 여쭤봅니다.

**Comment by MerHS** [comment]
정수 데이터의 조작은 모두 스칼라의 `Int`를 그대로 따라가며 overflow가 나는 인풋은 없다고 가정해주시면 됩니다.

**Comment by simnalamburt** [comment]
감사합니다
